# Generated by Django 5.2.7 on 2025-11-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_remove_networknode_hierarchy_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
    ]
