# Generated by Django 5.2.7 on 2025-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_networknode_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="networknode",
            name="node_type",
            field=models.IntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Розничная сеть"),
                    (2, "Индивидуальный предприниматель"),
                ],
                default=0,
                verbose_name="Тип звена",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=19,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="network.product", verbose_name="Продукты"
            ),
        ),
    ]
