# Generated by Django 5.2.7 on 2025-11-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_networknode_node_type_alter_networknode_debt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="node_type",
        ),
    ]
